"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type, TypeVar
from resotoclient.models import JsValue

T = TypeVar("T")
def json_load(json_obj: object, cls: Optional[Type[T]] = ...) -> T:
    ...

def json_loadb(json_obj: bytes, cls: Optional[Type[T]] = ...) -> T:
    ...

def json_dump(obj: object, cls: Optional[type] = ...) -> JsValue:
    ...

