"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Tuple

def key_from_psk(psk: str, salt: Optional[bytes] = ...) -> Tuple[bytes, bytes]:
    """Derive a 256 bit key from a pass"""
    ...

def encode_jwt(payload: Dict[str, Any], psk: str, headers: Optional[Dict[str, str]] = ..., expire_in: int = ...) -> str:
    """Encodes a payload into a JWT and"""
    ...

def encode_jwt_to_headers(http_headers: Dict[str, str], payload: Dict[str, Any], psk: str, scheme: str = ..., headers: Optional[Dict[str, str]] = ..., expire_in: int = ...) -> Dict[str, str]:
    """Takes a payload and psk turns th"""
    ...

def decode_jwt(encoded_jwt: str, psk: str, options: Optional[Dict[str, Any]] = ...) -> Dict[str, Any]:
    """Decode a JWT using a key derived"""
    ...

def decode_jwt_from_headers(http_headers: Dict[str, str], psk: str, scheme: str = ..., options: Optional[Dict[str, Any]] = ...) -> Optional[Dict[str, str]]:
    """Retrieves the Authorization head"""
    ...

def decode_jwt_from_header_value(authorization_header: str, psk: str, scheme: str = ..., options: Optional[Dict[str, Any]] = ...) -> Optional[Dict[str, str]]:
    """Decodes a JWT payload from a htt"""
    ...

