name: Check PR (resotoclient)
on:
  push:
    branches:
        - main
  pull_request:

jobs:
  resotoclient:
    name: "resotoclient"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: $\{\{runner.os}}-poetry-$\{\{hashFiles('poetry.lock')}}
          restore-keys: |
            $\{\{ runner.os }}-poetry-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry nox nox-poetry

      - name: Run nox
        working-directory: .
        run: nox
